# Document head settings
head:
  css: !!seq
    - assets/css/index.css
    - assets/css/external.css
  js:

# Site settings
title: Klise Theme # site title
description: >- # site description
  He's writing in Bahasa about web technology and experience as a journal 
  for documentation things that he learned, meet him <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone

# Setting static site generator
lulu:
  markdown_lint:
    empasis: "*"
    strong: "*"
    no-consecutive-blank-lines: false
